version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "8005:8005"
    expose:
      - "8005"
    restart: always

  notification:
    build:
      context: .
      dockerfile: Dockerfile.notification
    environment:
      - ENV=${ENV:-local}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - APP_NAME=${APP_NAME}
    volumes:
      - ./users.db:/app/users.db
    restart: unless-stopped
    depends_on:
      - app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
