version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
